config/routes.rb
Rails.application.routes.draw do
  resources :cash_donations
  resources :donors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash_donation.rb
class CashDonation < Gift
end

app/models/donor.rb
class Donor < ApplicationRecord
  has_many :gifts
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :donor
  scope :cash_donations, -> { where(type: 'CashDonation') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cash_donations_controller.rb
class CashDonationsController < ApplicationController
  before_action :set_cash_donation, only: [:show, :edit, :update, :destroy]

  # GET /cash_donations
  # GET /cash_donations.json
  def index
    @cash_donations = CashDonation.all
  end

  # GET /cash_donations/1
  # GET /cash_donations/1.json
  def show
  end

  # GET /cash_donations/new
  def new
    @cash_donation = CashDonation.new
  end

  # GET /cash_donations/1/edit
  def edit
  end

  # POST /cash_donations
  # POST /cash_donations.json
  def create
    @cash_donation = CashDonation.new(cash_donation_params)

    respond_to do |format|
      if @cash_donation.save
        format.html { redirect_to @cash_donation, notice: 'Cash donation was successfully created.' }
        format.json { render :show, status: :created, location: @cash_donation }
      else
        format.html { render :new }
        format.json { render json: @cash_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cash_donations/1
  # PATCH/PUT /cash_donations/1.json
  def update
    respond_to do |format|
      if @cash_donation.update(cash_donation_params)
        format.html { redirect_to @cash_donation, notice: 'Cash donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash_donation }
      else
        format.html { render :edit }
        format.json { render json: @cash_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cash_donations/1
  # DELETE /cash_donations/1.json
  def destroy
    @cash_donation.destroy
    respond_to do |format|
      format.html { redirect_to cash_donations_url, notice: 'Cash donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash_donation
      @cash_donation = CashDonation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_donation_params
      params.require(:cash_donation).permit(:amount_in_cents, :donor_id, :description, :notes, :given_at)
    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name, :email, :mailing_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_donations_helper.rb
module CashDonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/cash_donations/_form.html.erb
<%= form_with(model: cash_donation, local: true) do |form| %>
  <% if cash_donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cash_donation.errors.count, "error") %> prohibited this cash_donation from being saved:</h2>

      <ul>
      <% cash_donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount_in_cents %>
    <%= form.number_field :amount_in_cents %>
  </div>

  <div class="field">
    <%= form.label :donor_id %>
    <%= form.text_field :donor_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :given_at %>
    <%= form.datetime_select :given_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cash_donations/edit.html.erb
<h1>Editing Cash Donation</h1>

<%= render 'form', cash_donation: @cash_donation %>

<%= link_to 'Show', @cash_donation %> |
<%= link_to 'Back', cash_donations_path %>

app/views/cash_donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cash Donations</h1>

<table>
  <thead>
    <tr>
      <th>Amount in cents</th>
      <th>Donor</th>
      <th>Description</th>
      <th>Notes</th>
      <th>Given at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cash_donations.each do |cash_donation| %>
      <tr>
        <td><%= cash_donation.amount_in_cents %></td>
        <td><%= cash_donation.donor_id %></td>
        <td><%= cash_donation.description %></td>
        <td><%= cash_donation.notes %></td>
        <td><%= cash_donation.given_at %></td>
        <td><%= link_to 'Show', cash_donation %></td>
        <td><%= link_to 'Edit', edit_cash_donation_path(cash_donation) %></td>
        <td><%= link_to 'Destroy', cash_donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cash Donation', new_cash_donation_path %>

app/views/cash_donations/new.html.erb
<h1>New Cash Donation</h1>

<%= render 'form', cash_donation: @cash_donation %>

<%= link_to 'Back', cash_donations_path %>

app/views/cash_donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount in cents:</strong>
  <%= @cash_donation.amount_in_cents %>
</p>

<p>
  <strong>Donor:</strong>
  <%= @cash_donation.donor_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cash_donation.description %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @cash_donation.notes %>
</p>

<p>
  <strong>Given at:</strong>
  <%= @cash_donation.given_at %>
</p>

<%= link_to 'Edit', edit_cash_donation_path(@cash_donation) %> |
<%= link_to 'Back', cash_donations_path %>

app/views/donors/_donor.html.erb
<tr>
  <td><%= link_to donor.name, edit_donor_path(donor) %></td>
  <td><%= donor.email %></td>
  <td><%= donor.mailing_address %></td>
  <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<tr>
  <td colspan=2>Gifts: <%= donor.gifts.count %></td>
  <td colspan=2>Cash: <%= donor.gifts.cash_donations.count %></td>
<tr>

app/views/donors/_form.html.erb
<%= form_with(model: donor, local: true) do |form| %>
  <% if donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mailing_address %>
    <%= form.text_area :mailing_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mailing address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= render @donors %>
  </tbody>
</table>

<br>

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>

<p>
  <strong>Mailing address:</strong>
  <%= @donor.mailing_address %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonorManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>